mapERRORFunction2Code () {
        funcName=$1
        type=$2
        case "$funcName" in 
                mine)
                                code=1500
                                name=mine
                                ;;
                mineGenesis)
                                code=1501
                                name=mineGenesis
                                ;;
                checkAccountBal)
                                code=1510
                                name=checkAccountBal
                                ;;
                getTransactionMessageForSign)
                                code=1511
                                name=getTransactionMessageForSign
                                ;;
                AddTransactionFromNetwork)
                                code=1512
                                name=AddTransactionFromNetwork
                                ;;
                pushSignedMessageToPending)
                                code=1513
                                name=pushSignedMessageToPending
                                ;;
                askBlockContent)
                                code=1514
                                name=askBlockContent
                                ;;
                provideTXMessage)
                                code=1515
                                name=provideTXMessage
                                ;;
                AddNewBlockFromNode)
                                code=1520
                                name=AddNewBlockFromNode
                                ;;
                listNewBlock)
                                code=1521
                                name=listNewBlock
                                ;;
                provideBlockContent)
                                code=1522
                                name=provideBlockContent
                                ;;
                validateNetworkBlockHash)
                                code=1523
                                name=validateNetworkBlockHash
                                ;;
                askBlockContent)
                                code=1524
                                name=askBlockContent
                                ;;
                updateNetworkInfo)
                                code=1401
                                name=updateNetworkInfo
                                ;;
                *)
                                code=000
                                ;;
                esac
        echo $code
}
